# Generated by Django 4.2 on 2023-04-20 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_alter_perfil_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='cpf',
        ),
    ]
