# Generated by Django 4.2 on 2023-04-20 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0003_remove_perfil_bairro_remove_perfil_cep_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='endereco',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='perfil',
            old_name='numero',
            new_name='address2',
        ),
        migrations.RenameField(
            model_name='perfil',
            old_name='idade',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='perfil',
            old_name='complemento',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='perfil',
            old_name='data_nascimento',
            new_name='date_of_birth',
        ),
    ]
