# Generated by Django 4.2 on 2023-04-14 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_order_itemordered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.DeleteModel(
            name='ItemOrdered',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
