# Generated by Django 4.2 on 2023-04-14 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_order_user_delete_itemordered_delete_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('V', 'variable'), ('S', 'simple')], default='V', max_length=1),
        ),
    ]
