# Generated by Django 4.2 on 2023-04-20 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_itemordered_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemordered',
            name='amount',
        ),
        migrations.AlterField(
            model_name='itemordered',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
